# Generated by Django 5.2.2 on 2025-06-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(default=1234, upload_to='blog_media'),
            preserve_default=False,
        ),
    ]
