# Generated by Django 5.2.2 on 2025-06-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_logintable_userprofile_delete_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
