# Generated by Django 5.2.2 on 2025-06-18 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0008_blog_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='blog_media')),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Userprofile',
        ),
        migrations.RemoveField(
            model_name='logintable',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='logintable',
            name='type',
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.blog'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.logintable'),
        ),
    ]
