# Generated by Django 5.2.2 on 2025-06-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_usertable_delete_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
